version: "3.2"
services:
  # postgres
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=checkin-system
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - checkin-system-network

  # backend
  backend:
    build:
      context: ./backend
      dockerfile: "Dockerfile"
    image: quay.io/d_rk/checkin-system-backend
    restart: unless-stopped
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_DRIVER=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=checkin-system
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - CORS_ALLOWED_ORIGINS=*
    networks:
      - checkin-system-network

  # frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: "Dockerfile"
    image: quay.io/d_rk/checkin-system-frontend
    restart: unless-stopped
    links:
      - backend
    ports:
      - "3000:80"
    networks:
      - checkin-system-network

  # rfid-reader
  rfid-reader:
    build:
      context: ./raspi/rfid_reader
      dockerfile: "Dockerfile"
    image: quay.io/d_rk/checkin-system-reader
    restart: unless-stopped
    privileged: true
    links:
      - backend
    networks:
      - checkin-system-network
# volume for db data
volumes:
  db:
    driver: local

networks:
  checkin-system-network:
    driver: bridge
