version: "3.2"
services:
  # postgres
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=checkin-system
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # backend
  backend:
    build:
      context: ./backend
      dockerfile: "Dockerfile"
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_DRIVER=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=checkin-system
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - CORS_ALLOWED_ORIGINS=*

  # frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    volumes:
      - ./:/backend

# volume for db data
volumes:
  db:
    driver: local
